# Generated by Django 5.2.16 on 2026-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='friendrequest',
            name='accounts_fr_receive_c0de5e_idx',
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['receiver'], name='accounts_fr_receive_ad231e_idx'),
        ),
        migrations.AddIndex(
            model_name='friendrequest',
            index=models.Index(fields=['sender'], name='accounts_fr_sender__339929_idx'),
        ),
    ]
