[project]
name = "chat-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "channels>=4.3.2",
    "channels-redis>=4.3.0",
    "dj-database-url>=3.1.2",
    "dj-rest-auth[with-social]>=7.2.0",
    "django-allauth[socialaccount]>=65.18.0",
    "django-cleanup>=9.0.0",
    "django-cors-headers>=4.9.0",
    "django-filter>=26.1",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.30.0",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.12",
    "python-decouple>=3.8",
    "redis>=8.0.1",
    "uvicorn[standard]>=0.51.0",
    "whitenoise>=6.12.0",
]
