# Generated by Django 5.2.16 on 2026-07-27 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_read_by', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['type'], name='conversatio_type_65d44c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['name'], name='conversatio_name_6ce628_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['role'], name='conversatio_role_cef330_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('user', 'conversation')},
        ),
    ]
